---

- name: Base Raspbian Buster Config
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: su

  gather_facts: false
  tasks:

    - name: Create user severs
      user:
        name: severs
        shell: /bin/bash
        groups: admins
        append: yes
        create_home: True