---

- name: Base Raspbian Buster Config
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: su

  gather_facts: false
  tasks:

    - name: Create user severs
      user:
        name: severs
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: True

    - name: Create .ssh directory
      file:
        path: /home/severs/.ssh
        state: directory
        owner: severs
        group: severs
        mode: 0700

    - name: Authorized keys file
      copy:
        src: severs.pub.rsa
        dest: /home/severs/.ssh/authorized_keys
        owner: severs
        group: sudo
        mode: 0600

    - name: remove password requirement for sudo group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo\s'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
