---

- name: Base Raspbian Buster Config
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: su

  gather_facts: false
  tasks:

    - name: Create user severs
      user:
        name: severs
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: True

    - name: Authorized keys file
      copy:
        src: resources/default_profile/
        dest: /home/severs/
        owner: severs
        group: severs
        mode: 0700

    - name: remove password requirement for sudo group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo\s'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
