---

- name: Base Raspbian Buster Config
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: su

  gather_facts: false

  vars:
    user: severs
  tasks:

    - name: Generate US locale
      locale_gen:
        name: "en_US.UTF-8"
        state: present

    - name: Install required packages
      apt:
        pkg:
          - zsh

    - name: Create user
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh
        groups: sudo
        append: yes
        create_home: True

    - name: Setup user profile
      copy:
        src: ../common/resources/default_profile/
        dest: /home/{{ user }}/
        owner: severs
        group: severs
        mode: 0700

    - name: remove password requirement for sudo group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo\s'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'

    - name: Disable password login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
